### ISSUE TITLE
Add project: pydance

### ISSUE THREAD

**Issue by peterwwillis** [mahmoud/awesome-python-applications#18]
## Basic info

**Application name**: pydance
**Application repo link**: https://icculus.org/pyddr/download.php#source
**Application home link**:https://icculus.org/pyddr/
**Application description**: A Python implementation of the game "Dance Dance Revolution"

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [ ] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

This game is old, but it used to be popular as an open-source Linux alternative to similar Windows-based games (such as StepMania). Uses the pygame library and SDL for rendering. Supports hardware game controllers. Package dependencies were available for Debian and Gentoo, and one release for Slackware.

Now made obsolete by StepMania's support for Linux, and probably that not a lot of people play this game anymore. Subversion repository seems to be missing but the last source code release is still available for download.

---

**Comment by mahmoud** [comment]
Hey DDR, nice! Never had the quarters for the real thing, maybe if I'd had this I'd've gotten any good. :)

Anyways, back to the list-worthiness, I did find one semi-maintained fork of it over here on github, and it does have the full history: https://github.com/mbenkmann/pydance

I still need to think about whether to include this, as not only is maintenance shaky, but it's harder to make an exception because, correct me if I'm wrong, but I think the pygame architecture of such a pygame-based rhythm game is well-demonstrated in the much more maintained [fofix](https://github.com/fofix/fofix). What do you think?

**Comment by peterwwillis** [comment]
Fofix definitely has more active development, and appears more like a "modern" python project. If you only had to cover one such game, I'd do Fofix, with pydance more of a historical example that python has long been a successful game platform.

**Comment by mahmoud** [comment]
Agreed. I added a note about pydance in the projects.yaml. I think down the line we'll want "see also" type functionality and pydance would be great for that. Thanks again for bringing this project to my attention!
